[project]
name = 'Antimatter-Harvesting-and-Containment-Simulator'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.antimatter-production]
path = 'contracts/antimatter-production.clar'
clarity_version = 2
epoch = 2.5

[contracts.containment-protocol]
path = 'contracts/containment-protocol.clar'
clarity_version = 2
epoch = 2.5

[contracts.energy-conversion]
path = 'contracts/energy-conversion.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
